# Copyright 2023-2024 Chris Croome
#
# This file is part of the Webarchitects /etc/hosts Ansible role.
#
# The Webarchitects /etc/hosts Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects /etc/hosts Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects /etc/hosts Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Check variables
  block:

    - name: Loop though the proposed /etc/hosts file lines
      ansible.builtin.assert:
        that:
          - etchosts_entry_check.hostname is defined
          - etchosts_entry_check.hostname != []
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      loop: "{{ etchosts_file }}"
      loop_control:
        loop_var: etchosts_entry_check
        label: "{{ etchosts_entry_check.ip }}"
      when: >-
        ( ( etchosts_entry_check.state is not defined ) or
        ( etchosts_entry_check.state == "present" ) )

    - name: Slurp a base64 encoded version of the /etc/hosts file
      ansible.builtin.slurp:
        src: /etc/hosts
      register: etchosts_existing_b64encoded

    - name: Decode the base64 encoded version of the /etc/hosts file and set a variable
      ansible.builtin.set_fact:
        etchosts_existing: "{{ etchosts_existing_b64encoded['content'] | b64decode | community.general.jc('hosts') }}"
        etchosts_existing_ips: "{{ etchosts_existing_b64encoded['content'] | b64decode | community.general.jc('hosts') | community.general.json_query('[*].ip') }}"

    - name: Debug the existing /etc/hosts file entries
      ansible.builtin.debug:
        var: etchosts_existing
        verbosity: "{% if ansible_check_mode | bool %}2{% else %}3{% endif %}"

    - name: Diff the existing and proposed /etc/hosts file variables
      ansible.utils.fact_diff:
        before: "{{ etchosts_existing }}"
        after: "{{ etchosts_file }}"
      changed_when: false

    # TODO Add checks:
    # - Proposed IP addresses are not duplicated
    # - Domain names resolve to the server

  tags:
    - etchosts
...
