# Copyright 2023 Chris Croome
#
# This file is part of the Webarchitects /etc/hosts Ansible role.
#
# The Webarchitects /etc/hosts Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects /etc/hosts Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects /etc/hosts Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Amend /etc/hosts
  block:

    - name: Line present
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ etchosts_line }}"
        regex: "{{ etchosts_regex }}"
        state: present
        backup: true
        mode: "0644"
        owner: root
        group: root
      vars:
        etchosts_line: "{{ etchosts_entry.ip }}{% for etchosts_name in etchosts_entry.hostname %} {{ etchosts_name }}{% endfor %}"
        etchosts_regex: "^{{ etchosts_entry.ip | ansible.builtin.regex_escape() }}\\s+"
      when: >-
        ( ( etchosts_line.state is not defined ) or
        ( etchosts_line.state == "present" ) ) and
        ( ( etchosts_line.hostname is defined ) and
        ( etchosts_line.hostname != [] ) )

    - name: Line absent
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ etchosts_line }}"
        regex: "{{ etchosts_regex }}"
        state: absent
        backup: true
        mode: "0644"
        owner: root
        group: root
      vars:
        etchosts_line: "{{ etchosts_entry.ip }}{% for etchosts_name in etchosts_entry.hostname %} {{ etchosts_name }}{% endfor %}"
        etchosts_regex: "^{{ etchosts_entry.ip | ansible.builtin.regex_escape() }}\\s+"
      when:
        - etchosts_line.state is defined
        - etchosts_line.state == "absent"

  tags:
    - etchosts
...
